Mix.install([
  {:nimble_csv, "~> 1.1"}
])

# Definimos el parser para manejar comas y comillas dentro de los prompts
NimbleCSV.define(Coding5sParser, separator: ",", escape: "\"")

defmodule LabGenerator do
  require EEx

  # Template EEx para el archivo Markdown/Livebook
  # ACTUALIZACIÓN: Se agregó <details> para colapsar y ```text para el botón de copia
  EEx.function_from_string(
    :def,
    :render_livemd,
    """
    # 🟢 Coding5s Lab: Elixir Foundations (<%= level %>)

    ## 🧬 Stage 1: <%= type %> #<%= id %> - Learn - <%= topic %>

    ### 🤖 Coding5s Prompt (Stage 1)
    Expand the section below and copy the text in the code block. Paste it into your AI assistant.

    <details>
    <summary><strong>✨ Click to expand the Stage 1 Prompt</strong></summary>

    ```text
    <%= prompt %>
    ```

    </details>

    ---

    ### 💻 Live Execution
    Paste the code generated by the AI here to test it:

    ```elixir

    ```
    """,
    [:id, :type, :level, :topic, :prompt]
  )

  def run(csv_path) do
    unless File.exists?(csv_path) do
      raise "Archivo #{csv_path} no encontrado."
    end

    IO.puts("Iniciando la generación de laboratorios...")

    csv_path
    |> File.stream!()
    |> Coding5sParser.parse_stream(skip_headers: true)
    # Pasamos cada fila a nuestra función process_row
    |> Enum.each(&process_row/1)

    IO.puts("\n✅ ¡Todos los laboratorios interactivos han sido generados exitosamente!")
  end

# --- PATTERN MATCHING AL RESCATE ---

  # Molde 1: Fila con 5 columnas (ID, Nivel, Tipo, Tópico, Prompt)
  defp process_row([id, level, type, topic, prompt]) do
    # Quitamos los guiones bajos de id y type para capturarlos
    generate_file(id, level, type, topic, prompt)
  end

  # Molde 2: Fila con 4 columnas (Nivel, Tipo, Tópico, Prompt)
  defp process_row([level, type, topic, prompt]) do
    # Si por alguna razón la fila no tiene ID, le pasamos "00" para que no falle
    generate_file("00", level, type, topic, prompt)
  end

  # Molde 3: Catch-all. Si la fila está vacía o tiene un número raro de columnas.
  defp process_row(row) do
    IO.puts("⚠️ Saltando fila con formato inesperado (Columnas: #{length(row)})")
  end

  # --- LÓGICA DE GENERACIÓN ---

  # Actualizamos la función para recibir id y type
  defp generate_file(id, level, type, topic, prompt) do
    # Formatear el nivel (ej. " Beginner " -> "beginner")
    folder_level =
      level
      |> String.downcase()
      |> String.trim()

    # Formatear el nombre del archivo: combinamos tipo, id y topic ANTES del snake_case
    filename =
      "#{type}_#{id}_#{topic}"
      |> String.downcase()
      |> String.replace(~r/[^a-z0-9]+/, "_")
      |> String.trim("_")
      |> Kernel.<>(".livemd")

    # Crear directorios
    dir_path = Path.join(["labs", folder_level])
    File.mkdir_p!(dir_path)

    # Inyectar variables en el template
    content = render_livemd(id, type, level, topic, prompt)

    # Escribir archivo
    full_path = Path.join(dir_path, filename)
    File.write!(full_path, content)

    IO.puts("Generado: #{full_path}")
  end
end

# Ejecutamos el script
LabGenerator.run("massive.csv")
